title: Edulabs
description: Documentation simple et efficace
theme: just-the-docs

url: "https://callmevrm.github.io"
baseurl: "/edulabs.github.io"  # si ton repo s'appelle ainsi

aux_links:
  Template Repository: https://github.com/callmevrm/edulabs.github.io
